services:
  - type: web
    name: asin-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2
    envVars:
      - key: DATABASE_URL
        sync: false
